### ISSUE TITLE
Add @specialVars literals

### ISSUE THREAD

**Issue by rlbr** [cardillan/mindcode#114]
In mindcode this is invalid
```a = @graphite```

Hower in mindustry logic this is allowed:
```set a @graphite```

My current workaround for this is adding aaa__ to the start of something I want to be an `@literal` then substituting aaa__ with an "@"

**Comment by cardillan** [comment]
The `@` literals are supported in Mindcode. I've just tried the following code in the web app:

```
A = @graphite
print(A)
printflush(message1)
```

and this is the output:

```
set A @graphite
print A
printflush message1
end
```

Could you please post the code that gives you problems? Perhaps there's a bug that only shows in a more complex code. Are you using the web app or command line compiler?

**Comment by rlbr** [comment]
Sorry the error is specifically with ```@graphite.sensor(@id)```

**Comment by rlbr** [comment]
Closing

**Comment by cardillan** [comment]
> Sorry the error is specifically with `@graphite.sensor(@id)`

Oh, I see!

Actually I want this to be a valid syntax, but it requires updating the grammar. It is a similar problem to #92.
