### ISSUE TITLE
QoL: Inverse lookup operation

### ISSUE THREAD

**Issue by rlbr** [cardillan/mindcode#115]
In mindustry logic:
```lookup item result 0```
result would have ```@copper```
This is useful to store constants in memory since memory cells only support numbers

The "inverse" of this operation in mindustry logic would be: 
```sensor result @copper @id```
There would be 0 in result now.

Currently, no function looks like ```resource_num = sensor(@copper, @id)``` or ```resource_num = @copper.sensor(@id)``` This means to find the id of a ```@literal``` I must either:
1. Look it up in the wiki (yuck)
2. Use the workaround ```resource_num = aaa__copper.sensor(@id)```, then replace instances of *aaa__* in the generated code with "@", like in #114 

I think a fix would be a fake function ```id(@literal)``` that is replaced in the generated code with the corresponding number.

**Comment by cardillan** [comment]
At this moment, Mindcode doesn't recognize individual `sensor` values. Anything that goes after a dot is compiled into a `sensor` instruction. Therefore, no changes are needed to support the `id` property:

```
A = @graphite
b = A.id
print(b)
printflush(message1)
```

compiles into

```
set A @graphite
sensor b A @id
print b
printflush message1
end
```

Perhaps there's a problem with a more complex code. Please try to use `.id` in your own code and let ne know if it doesn't work.

**Comment by cardillan** [comment]
Just to add: it is possible to invoke the `.id` property directly on the `@` literal:

```
cell1[10] = @graphite.id
print(@coal.id)
```

compiles to

```
sensor __tmp0 @graphite @id
write __tmp0 cell1 10
sensor __tmp1 @coal @id
print __tmp1
end
```

I plan to add an optimization to replace the `sensor variable @constant @id` with the ID value for the built-in constant. That would do what you propose naturally.

**Comment by rlbr** [comment]
Thanks that's a good way of doing this
