### ISSUE TITLE
[Schematics] No option for blocks with changeable block type or unit mode

### ISSUE THREAD

**Issue by limonovthesecond2** [cardillan/mindcode#122]
There are some blocks that can have additional unit/block parameters. It can be unit to be built/spawned or a building to be built/spawned. For example, if any unit from nova or mono branch enters in any reconstructor, different unit modes are available for different units: move, repair, rebuild, assist player, mine and boost.

These blocks: payload-source, constructor, large-constructor, additive-reconstructor, multiplicative-reconstructor, exponential-reconstructor and tetrative-reconstructor

**Comment by cardillan** [comment]
Are these Serpulo schematics? This is something I wasn't aware of, could you please post some schematics created in Mindustry (either the ..msch file, or the text representation) with this feature? I'll need to understand how it behaves.

**Comment by limonovthesecond2** [comment]
All of them are Serpulo except for the constructor and the large-constructor. This options can be seen after clicking on the block.

Payload-source with `large-copper-wall`
![large-copper-wall](https://github.com/cardillan/mindcode/assets/118817903/7c41ca4f-5d6f-4c2d-85d2-7a40c9b1a399)
```
bXNjaAF4nA3JMQ6AIAwF0F+0LibexNXLGIcKHUgQCMXBw3k3fesDgweMWS4Fd7W+YQ5qvsXaY8kApiSnJoPbD8JS5UlFwmrlbl7/JsDBMeGlD89XEhA=
```

Payload-source with `eclipse`
![eclipse](https://github.com/cardillan/mindcode/assets/118817903/0f808f17-6bb1-4298-8514-77be434b5d53)
```
bXNjaAF4nA3JMQ6AIAwF0A9aFhMXz+HsYYxDgQ4kCITi4O31rQ8EmjAXvgU0RMeBJYqGntpItQBwmb1khT0vg7XxmyvHXevTg/xtAAtLDpv5AM5SEWw=
```

Oct options
![oct](https://github.com/cardillan/mindcode/assets/118817903/90e78245-b6b5-4d30-b493-a0462e78e1ac)
```
bXNjaAF4nA3KwQ2AIBAEwEXQhFgAVViAtRgfiPcgQTDHav0674GHt3A1XoKR0rliPqUnzTdzqwCmEg8pHcO2GwQKNTK/sqikVjv1SWz6PwM4uABrPqXKFXk=
```

Mega options
![mega](https://github.com/cardillan/mindcode/assets/118817903/be1f8b3a-92b1-48b6-b251-499b378c8eeb)
```
bXNjaAF4nA3Kuw2AMAwFwJdAaFiBFRiAWRBFCC4sOR85DvODrj0EhAlziZkQjLodWB/qSbkZ1wJgkXiTdPjzctjyEOMmnKLxS7tSqqWbjmRV/+wA/3MfALgXbA==
```

Pulsar options
![Pulsar](https://github.com/cardillan/mindcode/assets/118817903/40facd00-8106-4374-9b28-31b9c662d039)

```
bXNjaAF4nBXKQQ5AMBAF0F/Fxp5TSDiPWFQ7i0mqlZnh/Eje8sHDe7QlnITeSG1dMCTSKHwZ1wKgz+GgrGi23WEMKbHxQ7NQrEVN7mhVvuZ+bkLnXpB6FQM=
```

Constructor with `beam-node`
![constructor ](https://github.com/cardillan/mindcode/assets/118817903/e5e1c22d-6fa6-4c39-8a16-9f8d1313920a)
```
bXNjaAF4nBXJwQ2AIAwF0F9RLizhCsxjPCD2QILFtHV/NXm3h4AQMEu5GNHZPGekk61qu70NARB7Obgbpm0npDrEXJ/qQ7+jHy1EK72crxC2
```

Large-constructor with `spectre`
![spectre](https://github.com/cardillan/mindcode/assets/118817903/886a6031-5340-4c81-8014-080bbf55c0ed)

```
bXNjaAF4nA3KMQ6AIAwF0F8UFicP4qAncTcOiI0hQTBtvb+++cHDd+hrvBnBWG1eMJysSfJjuVUAocSDi8JtO2EsUS6eUqtq8iZr8g8CHJwnWukDJdkTKw==
```


Scheme with all blocks need to test:
```
bXNjaAF4nG1My0rEMBQ9aZu009ZhRsRBcOHGZb9IXMTkMgbSJqRp1b83KYqDzObe88YzbkpUkxwJ7dnEYVbvlHCnaVbB+GjcBEBY+UZ2RvHy2mHvVgo6mJUG7XLWRBqH2S1BEXrvPij8sr2XX9ZJ/ef+8NUZjXuptYl5J5By0xzDoqIL6C7J47jYaLw1Sl6JHq0MZxoupQf69G6iKRpp/6VPkWK4NgMcAYY2H6DnwA5Fwn2TlWJTOpQQKLjAHStQgW9eBZG8ckP11ktKHuLpCbASfV4SqV6D8fQ6sBqHFGENbrO3wynVWIsnNGDfT2leaA==
```

**Comment by cardillan** [comment]
Thanks! I didn't know these settings exist.

This will require updating Schemacode grammar to support the new settings. It might take some time to fix. Maybe I could update the decompiler not to crash on these schematics first.
