### ISSUE TITLE
Optimiser doesn't realize assignment can be skipped

### ISSUE THREAD

**Issue by tom-leys** [cardillan/mindcode#133]
This code correctly gets correctly unrolled. However there is an obvious optimization step missing. It does not realize when a temporary variable assignment is a constant and move that constant into later instructions instead.

Also, thanks for the great tool. I'm loving working in mindcode. Really appreciated ! ❤️ 

Output subsection:
```
set __tmp0 SORT_1
set __tmp1 CONV_1
sensor item_type __tmp0 @config
sensor item_count CONTAINER item_type
op lessThan under_limit item_count QTY_LIMIT
control enabled __tmp1 under_limit 0 0 0
```
Expect

```
sensor item_type SORT_1 @config
sensor item_count CONTAINER item_type
op lessThan under_limit item_count QTY_LIMIT
control enabled CONV_1 under_limit 0 0 0
```

Full code:
```
QTY_LIMIT = 300 // How many to store in the container of each type
CONTAINER = vault1
SORT_1 = sorter1
CONV_1 = conveyor1
SORT_2 = sorter2
CONV_2 = conveyor2
SORT_3 = sorter3
CONV_3 = conveyor3

for n in 1 .. 3
    sort = case n
        when 1
            SORT_1
        when 2
            SORT_2
        when 3
            SORT_3
    end
    conv = case n
        when 1
            CONV_1
        when 2
            CONV_2
        when 3
            CONV_3
    end

    item_type = sort.config
    item_count = CONTAINER.sensor(item_type)
    under_limit = item_count < QTY_LIMIT
    conv.enabled = under_limit
end
```

Output is 

```
set QTY_LIMIT 300
set CONTAINER vault1
set SORT_1 sorter1
set CONV_1 conveyor1
set SORT_2 sorter2
set CONV_2 conveyor2
set SORT_3 sorter3
set CONV_3 conveyor3
set __tmp0 SORT_1
set __tmp1 CONV_1
sensor item_type __tmp0 @config
sensor item_count CONTAINER item_type
op lessThan under_limit item_count QTY_LIMIT
control enabled __tmp1 under_limit 0 0 0
set __tmp0 SORT_2
set __tmp1 CONV_2
sensor item_type __tmp0 @config
sensor item_count CONTAINER item_type
op lessThan under_limit item_count QTY_LIMIT
control enabled __tmp1 under_limit 0 0 0
set __tmp0 SORT_3
set __tmp1 CONV_3
sensor item_type __tmp0 @config
sensor item_count CONTAINER item_type
op lessThan under_limit item_count QTY_LIMIT
control enabled __tmp1 under_limit 0 0 0
end
```

I tried adding 
```
#set passes = 10 // Many passes to unroll and tidy this loop.
#set optimization = aggressive
``` 
To the start of the code, to no avail

**Comment by tom-leys** [comment]
Changing the variable names to lowercase (so not global) did not resolve this issue.

**Comment by cardillan** [comment]
Thank you very much for reporting the issue! My codebase I can use to test the compiler and optimizer is still not that large, so I easily miss bugs that arise from constructs I don't use. I hope I'll be able to look into it this or next weekend.

As a workaround it is possible to rewrite the code like this:

```
QTY_LIMIT = 300 // How many to store in the container of each type
CONTAINER = vault1
SORT_1 = sorter1
CONV_1 = conveyor1
SORT_2 = sorter2
CONV_2 = conveyor2
SORT_3 = sorter3
CONV_3 = conveyor3

processConveyor(CONV_1, SORT_1)
processConveyor(CONV_2, SORT_2)
processConveyor(CONV_3, SORT_3)

inline def processConveyor(conv, sort)
    item_type = sort.config
    item_count = CONTAINER.sensor(item_type)
    under_limit = item_count < QTY_LIMIT
    conv.enabled = under_limit
end
```

**Comment by tom-leys** [comment]
Wonderful! I'll try this workaround. Given your interested reply I'll post my compiler bug now.

Edit: Your approach does indeed output lovely code.

**Comment by cardillan** [comment]
A fix is ready. I'll wait with a new release for a while to see whether I'd be able to fix #135 as well.

**Comment by tom-leys** [comment]
Nice one! No rush :)

**Comment by cardillan** [comment]
For future reference: the bug is caused by the Data Flow Optimizer processing the implicit `else` branch of the case statement. This branch is unreachable, but it is still processed by the DFO. This causes the `__tmp0` variable to have multiple definitions and therefore makes it non-eligible for elimination. The unreachable code is removed by the respective optimizer, which is run after the Data Flow Optimizer, leaving the `_tmp0` variable there.

As a fix, the DFO gets the information about unreachable code. Unreachable AST contexts do not contribute to variable states.

**Comment by tom-leys** [comment]
Potentially the DFO should run after you've eliminated all the code you can ... :)

It's hard to sequence these things. I can see why there is benefit to running them all twice.

**Comment by cardillan** [comment]
> Potentially the DFO should run after you've eliminated all the code you can ... :)

Unfortunately some of the the optimizations, including the DFO, rely on the structure of the code as generated by the compiler. Removing the unreachable code generally breaks that structure, which is why it has to run as one of the last optimizations steps. :(

(As this is a hobby project, I've cut a lot of corners and did a lot of things in a kind of unorthodox way. If the program size wasn't limited to 1000 instructions, I could run into serious performance issues with the optimizations :D)

**Comment by tom-leys** [comment]
> As this is a hobby project ...

I bet you have learned a hell of a lot and had a great time. I think you've done perfect. Any first stab at a problem is going to need a re-write if you want to get something "ideal"
