### ISSUE TITLE
If Custom Functions can return a number, then they are broken

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#14]
Good evening @francois 

if I understand Custom Functions the right way and they are able to return a result:

```
allocate stack in cell1
// Just return the number 123
def test(n)
  123
end
```
then Custom Functions are broken :-(

#### The following test code needs:
* message1
* cell1

#### The code just does:
* Display "Initializing App"
* Display a counter
* If the call `// res = test(1)` is activated then the script stops working

```
allocate stack in cell1

// Just return the number 123
def test(n)
  123
end

print("\nInitializing App")
printflush(message1)

// If the following line is activated, then the script stops working
// res = test(1)

print("\ntest: ", res)

ProcessLoop += 1
print("\nProcessLoop: ", ProcessLoop)

printflush(message1)
```

Thanks a lot, kind regards,
Thomas

**Comment by francois** [comment]
Thanks for the bug report. I don't really know what's going on yet. Disabling optimizations does not resolve the issue. There is something deeper going on, maybe an assumption I make about cells. This will to be investigated further. Thanks again for your time, making Mindcode work better :)

**Comment by schittli** [comment]
I was also trying to understand what the generated code is doing and I got lost somewhere along the way....

But actually, it's good news that it's not the optimiser that causes the problem because then the troubleshooting would probably be more complicated 😅

I was hoping you could enable a trace/log mode that annotates/describes the generated code.
For example, for the code example in this issue, the compiler generates this code block (the stack is allocated this way: `allocate stack in cell1`):
```
read __tmp8 cell1 63
op add __tmp13 __tmp8 1
write __tmp13 cell1 63
```

The cause of this block is probably a higher-level function, (I am fantasising) e.g. to increment the stack pointer. Then maybe the code generator could add a comment just for debugging:
```
// Increment Stack Pointer
read __tmp8 cell1 63
op add __tmp13 __tmp8 1
write __tmp13 cell1 63
// …
```

Perhaps the idea does not fit into the concept of the compiler or would be very difficult to implement. Maybe it helps :-)

**Comment by cyclotron3k** [comment]
I was just looking at this too. If you have a look at [this sample program](https://mindcode.herokuapp.com/?s=28dada0f-21c7-457a-b82f-0ecda6195bfc), you'll see the following (I've added annotations):

    write 63 cell1 63             // cell1[63] = 63
    set count 0                   // 
    set __tmp3 1                  // 
    jump 27 notEqual __tmp3 true  // 
    op add count count 1          // 
    print "count: "               // 
    print count                   // 
    printflush message1           // 
    set __tmp7 1                  // 
    set __tmp8 60                 // 
    read __tmp9 cell1 63          // __tmp9 = 63
    op sub __tmp13 __tmp9 1       // __tmp13 = 62
    write 23 cell1 __tmp13        // cell1[62] = 23 // callback
    write __tmp9 cell1 63         // cell1[63] = 63
    read __tmp15 cell1 63         // __tmp15 = 63
    op sub __tmp19 __tmp15 1      // __tmp19 = 62
    write __tmp7 cell1 __tmp19    // cell1[62] = 1
    write __tmp15 cell1 63        // cell1[63] = 63
    read __tmp21 cell1 63         // __tmp21 = 63
    op sub __tmp25 __tmp21 1      // __tmp25 = 62
    write __tmp8 cell1 __tmp25    // cell1[62] = 60
    write __tmp21 cell1 63        // cell1[63] = 63

It looks like the stack pointer is not being updated correctly, and the function parameters are overwriting each-other?

**Comment by francois** [comment]
Hey! You’re great at debugging! I suggest you look at this test:

https://github.com/francois/mindcode/blob/a3ce5eecee12430e1d1f70f76931cc834dbce86b/src/test/java/info/teksol/mindcode/mindustry/LogicInstructionGeneratorTest.java#L647

it explains what happens in the generated code. I suspect this will help you understand what the code is supposed to do.

Cheers!
