### ISSUE TITLE
Some ucontrol functions don't work

### ISSUE THREAD

**Issue by IotaBread** [cardillan/mindcode#15]
Currently, these functions don't work and using them results the error `Unknown ucontrol opcode`. 

- [x] `payTake`
- [x] `payDrop`
- [x] `boost`
- [x] `pathfind`
- [x] `idle`
- [x] `stop`

They already are handled in `LogicInstructionGenerator`, but aren't handled by `DeadCodeEliminator#visitUcontrol`, where the exception is thrown.
https://github.com/francois/mindcode/blob/cc56523ce82547292f802023ec458727a47ca69d/src/main/java/info/teksol/mindcode/mindustry/DeadCodeEliminator.java#L293-L343

**Comment by francois** [comment]
Ah, yes. The optimizer doesn’t fully know what to so with those. I’ll fix then. It’s not difficult. Thanks for the bug report!
