### ISSUE TITLE
Direct Access to the Sensor() function would be useful

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#16]
Good evening

This is a _nice to have_ suggestion.

It's great that mindcode abstracts the mindustry logic, but with the sensor function, it would be great if one could call it directly. The background is that sometimes things are computed at runtime. For example, we dynamically calculate which resource is required. Next, we must know if a building contains this resource:

```
// At runtime, we have calculated that we need lead
RequiredRessource = @lead

// How can we test if a building contains this resource?
// Something like this would be great:
RessourceStock = sensor(factory1, RequiredRessource)

// The actual solutions is verbose:
RscStock = case RequiredRessource
when @silicon
  factory1.silicon
when @lead
  factory1.lead
…
end
```

I find the possibility that abstraction can also make things more cumbersome interesting. I was never aware of that before.

**Comment by francois** [comment]
Yup! I know about that. I want to enable this, but I haven’t found the right syntax yet. I’m thinking about it!

François

**Comment by cyclotron3k** [comment]
How about `factory1.sense(someResource)` ?

**Comment by schittli** [comment]
> How about `factory1.sense(someResource)` ?

I would also have chosen this syntax because it stays with the OO concept.

If it is too much effort, then I would simply offer as an alternative that you can call these commands 1:1 in mindcode. 
However, this approach may also be time-consuming because, depending on the context, the Mindustry Logic function parameters are used as normal parameters to pass values to the function, and sometimes a result is returned via the parameters. This could be tricky for the compiler...

**Comment by francois** [comment]
I am of two minds. I like the hash syntax:

```
resource = @coal
numcoal = CONTAINER[resource]
```

If we were to go with the function call syntax, then I would name the function `sensor`, to re-use the same terms as in Mindustry itself. This would lower the number of things that are different between Mindcode and Mindustry.

Any preference?

**Comment by cyclotron3k** [comment]
I agree `sensor` would be better than `sense`. Also, I quite like the hash syntax too! Hadn't thought of that.

**Comment by francois** [comment]
In the end, the hash syntax was much harder to implement. Instead, I chose to use the word `sensor`, and make it the "main" way to sense things. The `vault1.silicon` syntax is the shortcut syntax. People don't need to know that this syntax was the first one ;)

**Comment by schittli** [comment]
**Thank you very much for this great update!**, it is very useful :-)
