### ISSUE TITLE
A compilation error occurred when I used getBlock, making the code unable to function.

### ISSUE THREAD

**Issue by zhraa11** [cardillan/mindcode#178]
A compilation error occurred when I used getBlock, making the code unable to function.
mindcode:
A=0;
TYPE=0;
B=0;
C=0;
C=getBlock(0, 0,out type,out A);
if A==@stone && C==@air then
B=1;
end;

logic:
set A 0
set TYPE 0
set B 0
set C 0
ucontrol getBlock 0 0 type A 0
set C null
op equal __tmp1 A @stone
op equal __tmp2 C @air
op land __tmp3 __tmp1 __tmp2
jump 11 equal __tmp3 false
set B 1
end
print "Compiled by Mindcode - github.com/cardillan/mindcode"

**Comment by zhraa11** [comment]
it was compliated at https://mindcode.herokuapp.com/

**Comment by zhraa11** [comment]
it should be "ucontrol getBlock 0 0 type A C" instead of "ucontrol getBlock 0 0 type A 0"

**Comment by zhraa11** [comment]
This error caused an irreparable error in a large piece of my code

**Comment by cardillan** [comment]
Please add 

```
#set target = ML7A;
```

at the top of your code.

Explanation: the syntax of the `getBlock` function (and few others) has changed some time back. The original syntax returned the value from the `ucontrol getBlock` instruction in output parameters and the function didn't return any value. This syntax is still the default.

The `#set target = ML7A;` switches to newer syntax, where `getBlock` provides the found block as a return value, which is what you need. This will become the default eventually (probably in the next version; I should have actually made this change long time ago).

**Comment by cardillan** [comment]
In 2.7.0, the ML7A language target is the default one.
