### ISSUE TITLE
mindcode doesn't recognize playSound as described by the decompiler

### ISSUE THREAD

**Issue by 50275** [cardillan/mindcode#188]
`playsound(true, @sfx-bang, 1, 1, @thisx, @thisy, true);` -> Unknown function 'playsound'. got this from decompiler

whoops accidental pings.

**Comment by cardillan** [comment]
The `playsound` is a world processor instruction, and Mindcode by default compiles for standard processors. To switch to the world processor (and we need version 8 anyway) add `#set target = ML8AW;`:

```
#set target = ML8AW;
playsound(true, @sfx-bang, 1, 1, @thisx, @thisy, true);
```

I plan to introduce namespaces one day, moving the world processor functions into a different namespace, which would alleviate the need for setting the target using directives.

I'll probably "fix" it meanwhile by adding `#set target = ML8AW;` to every decompiler output.
