### ISSUE TITLE
Feature request: inline functions

### ISSUE THREAD

**Issue by cyclotron3k** [cardillan/mindcode#19]
Just an idea I had: inline functions. A bit like macros, they would replace the invocation of said function with a copy of the function.

This would serve two purposes: you wouldn't need a stack (or memory) and they could also return values other than numbers; they could also return objects.

Obviously, they couldn't be used in recursion.

**Comment by francois** [comment]
Is this what you mean?

```
def inline foo(n)
  2 * n
end

while true
  // some code
  curx = foo(2)
  cury = foo(4)
end
```

would compile down to something similar to:

```
while true
  // some code
  curx = 2 * 2
  cury = 2 * 4
```

This is feasible. Either this is done automatically, in which case the heuristic would probably be "do we save any Mindustry Logic steps", or we let the programmer decide. I think having the human decide is much easier to control. I'd go with that.

**Comment by cyclotron3k** [comment]
That's what I had in mind. Shall I close this now that you've moved it to the wishlist?

**Comment by francois** [comment]
Yeah, let's close and keep the project moving :)
