### ISSUE TITLE
Thanks a lot! • Question: Heap/Stack: Can we define the Memory-Cell/-Bank Block name in a Variable?

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#2]
Hello François 

**thank you _very_ much for your great work!,**

The syntax of the Mindustry Logic and the behavior of the commands is often terrible and so it is ingenious to have mindcode to fix the behavior of the Mindustry Logic commands :-)

It's great to have SW developers who knows how to program a compiler :-)

I have a question:
### Heap/Stack: Can we define the Memory-Cell/-Bank Block name in a Variable?
Here, we define the name of the assigned Memory-Cell/-Bank Block to `cell1`:
```
allocate heap in cell1[0 ... 16], stack in cell1[16 ... 64]
```

Because the name of this block can change in the game, it would be useful if we could something like this:

```
memBlockName = "cell2"
allocate heap in memBlockName[0 ... 16], stack in memBlockName[16 ... 64]
```

Because this code does not work, I guess it is not possible, 
#### therefore I share one idea I had:

You already use `$` as a prefix for global variables. Maybe you could define a prefix that defines a Text-Macro (which just replaces a keyword by its replacement string before the Code will be compiled), e.g. 
```
// The Compiler will replace `#memBlockName` with `cell2` before it startes compiling the code
#memBlockName = "cell2"
allocate heap in memBlockName[0 ... 16], stack in #memBlockName[16 ... 64]
```

Maybe a text macro function would open more useful possibility... But maybe it is also a stupid idea.

Thanks a lot, kind regards,
Thomas

**Comment by francois** [comment]
Thank you very much for this issue. I ran a test and it turns out this was actually possible. Please check the new version of `SYNTAX.markdown` and tell me if I explained how to use this feature clearly enough.

**Comment by schittli** [comment]
Thank you very much for your support and the updated Syntax sample!,
it works perfectly :-)
