### ISSUE TITLE
case … when … end: Commenting out 'when' makes the parser stumble

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#22]
Good afternoon

I just have a side note: I have found a somewhat troublesome oddity in the parser, it stumbles if we comment out `when`:

```
// This Code generates:
// Syntax error: [@3,6:9='case',<3>,2:0] on line 2:0: mismatched input 'case' expecting
n = 1
case n
  // when 1
  when 2
    print(2)
end
```

Thanks a lot, kind regards,
Thomas

**Comment by francois** [comment]
Hey, thanks for the report. Yes, this is a bug. This happens because comment AST nodes aren't properly ignored. I should be able to get to this shortly.

**Comment by schittli** [comment]
**Thank you very much**, @francois 
I was already afraid that this will be quite a tedious problem... it's great, you have AST under control, it works perfectly, now :-)
