### ISSUE TITLE
Optimizer: Variables are not always initialized

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#23]
Good morning

In the last two days, I suspected that my mind was slipping because I could no longer do the math. What a relief that the optimizer is probably a little too active in the variable initialization:

With this code:
```
x = 1
print("\n x: ", x)
print("\n x+x: ", x+x)
```
the compiler does not initialize the variable `x`, but it calculates afterwards with the uninitialized variables to get `x+x`:
```
set __tmp2 "\n x+x: "
print "\n x: "
print 1
op add __tmp3 x x
print __tmp2
print __tmp3
end
```

For the other readers: This small workaround (let's the compiler calculate the variable `x` by adding `0`) solves the problem:
```
x = 1 + 0
print("\n x: ", x)
print("\n x+x: ", x+x)
```

Thanks a lot, kind regards,
Thomas

**Comment by schittli** [comment]
I have a 2nd example, it looks like the optimizer mixes up two things.
Interesting are the lines 4 and 5:

```
1 varX = 99
2 print("\nvarX: ", varX)	     // OK: The game displays 99
3
4 copyVarX = varX                    // This assignment is removed in the compiled code
5 print("\ncopyVarX: ", copyVarX)    // Error: The game displays null
6 
7 printflush(message1)
```

This is the compiled code:

```
1 print "\nvarX: "
2 print 99
3 print "\ncopyVarX: "
4 print varX                         // Interesting: The Compiler uses varX (but it does not initialize this variable) 
                                     // and although the source code wants to output the variable copyVarX
5 printflush message1
6 end
```

**Comment by schittli** [comment]
btw: in general the compiler and optimizer works great, I have scripts with about 900 compiled lines and I guess that the Script-Bugs are more related to my logic than to the compiler :-)

**Comment by francois** [comment]
Hey! You’re very good at finding reproducible examples and that is a GREAT help!

The issue in this case is the DeadCodeEliminator. It isn’t intelligent enough to detect usages after the first use. I’ll take a look over the weekend.


Thanks again!
