### ISSUE TITLE
Compiling the mindcode project does not work since the release `"Prepared separate web application using Spring Web"`

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#27]
Good morning @francois 

Thanks a lot for all your work!, 
I have tried to compile mindcode and used your _Native installation_ guide. Until to the commit from Apr 12, 2021 `Permit "indirect" sensor references` compiling works perfectly:

```
git checkout 03ecee928ce36ae33303e2b37f428c2f63634adb
mvn clean compile exec:java
… everything Ok
```
But if I move to the next release, [Github Commit: `Prepared separate web application using Spring Web`](https://github.com/francois/mindcode/commit/ab1ad052502e8f24a404cc064ca9840316b38534) I get a compiler error:
```
git checkout ab1ad052502e8f24a404cc064ca9840316b38534
mvn clean compile exec:java

[INFO] Reactor Summary:                                                                                                                                    
[INFO]                                                                                                                                                     
[INFO] mindcode-compiler 1.0.0 ............................ FAILURE [  3.806 s]                                                                            
[INFO] webapp 0.0.1-SNAPSHOT .............................. SKIPPED                                                                                        
[INFO] Mindcode 1.0.0-SNAPSHOT ............................ SKIPPED                                                                                        
[INFO] ------------------------------------------------------------------------                                                                            
[INFO] BUILD FAILURE                                                                                                                                       
[INFO] ------------------------------------------------------------------------                                                                            
[INFO] Total time:  4.383 s                                                                                                                                
[INFO] Finished at: 2021-04-20T10:43:38+02:00                                                                                                              
[INFO] ------------------------------------------------------------------------                                                                            
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project mindcode-compiler: The parameters 'mainClass' for go
al org.codehaus.mojo:exec-maven-plugin:3.0.0:java are missing or invalid -> [Help 1]
…
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

Unfortunately, I don't know Maven at all, so it's a bit tricky to find the cause. About Java, I know the version is always important - it's fine, I guess:

```
java.exe -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
C:\GitWork\Clones\GitHub\Game - Mindustry - mindcode\src [(ab1ad05...)]

mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Portable\Java-Maven\apache-maven-3.6.3\bin\..
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: C:\Portable\Java-JDK\jdk-11
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

I can not attach a html-file with the output of `mvn clean compile exec:java -e` and `mvn clean compile exec:java -e -X`, therefore I have added a pdf, so that the colors are preserved - this is much easier to read.

[mvn clean compile exec_java -e -X.html.pdf](https://github.com/francois/mindcode/files/6342135/mvn.clean.compile.exec_java.-e.-X.html.pdf)
[mvn clean compile exec_java -e.html.pdf](https://github.com/francois/mindcode/files/6342136/mvn.clean.compile.exec_java.-e.html.pdf)

I really hope this is just a minor config issue. Please let me know if I can send you more information.

Thanks a lot, kind regards,
Thomas

**Comment by francois** [comment]
This was a temporary issue. I had some issues when I added the login/register experience. If you recompile using de1c3b0 you'll be fine. If not, please reopen this issue.

**Comment by schittli** [comment]
Thank you, @francois!, 
I think that I can not reopen issues.

No, unfortunately, the latest check-in [de1c3b0](https://github.com/francois/mindcode/commit/de1c3b0c6637bdadd90cf00133a78e97806f8f22) does not compile, I've got the reported error - I have just tested it again.

Please excuse me for not mentioning that this latest check-in ([de1c3b0](https://github.com/francois/mindcode/commit/de1c3b0c6637bdadd90cf00133a78e97806f8f22)) does not compile. As I have noticed this issue, I jumped back in the checkin-history and went forward until I've got the error - and this release was the last working release: [03ecee9](https://github.com/francois/mindcode/commit/03ecee928ce36ae33303e2b37f428c2f63634adb)

**Comment by francois** [comment]
I think the instructions are now outdated, and I haven't fixed them :(

Please try this:

```
$ ./mvnw clean test
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Mindcode                                                           [pom]
[INFO] mindcode-compiler                                                  [jar]
[INFO] mindcode-webapp                                                    [jar]
...
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ mindcode-webapp ---
[INFO] Loading execution data file /Users/francois/Projects/mindcode/webapp/target/jacoco.exec
[INFO] Analyzed bundle 'mindcode-webapp' with 18 classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Mindcode 1.0.0-SNAPSHOT ............................ SUCCESS [  0.070 s]
[INFO] mindcode-compiler 1.1.0-SNAPSHOT ................... SUCCESS [  6.120 s]
[INFO] mindcode-webapp 2.0.0-SNAPSHOT ..................... SUCCESS [ 15.755 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.109 s
[INFO] Finished at: 2021-04-20T12:09:04-04:00
[INFO] ------------------------------------------------------------------------
```

In order to achieve build success like this, you must have a PostgreSQL cluster available with a `mindcode_test` development database on it. @ByMartrixx kindly submitted instructions on how to use Docker to boot the database. Maybe that can help.

Once you have the above working, then you can try this:

```
$ ./mvnw install
$ java -classpath $( find webapp -type f -name '*.jar' | tr '\n' ':' ) info.teksol.mindcode.webapp.WebappApplication
```

This is Unix/Linux command line to say "find all the *.jar files under webapp/, then build a classpath such that: webapp/target/mindcode-webapp-2.0.0-SNAPSHOT.jar:webapp/target/dependency/spring-core-5.3.6.jar:..." and so on.

Since you're on Windows, `find` is not available, but I ran the command for you and as of de1c3b0c, this is the list of dependencies, as expressed for Windows:

```
java -classpath webapp\target\mindcode-webapp-2.0.0-SNAPSHOT.jar:webapp\target\dependency\spring-core-5.3.6.jar:webapp\target\dependency\maven-plugin-api-3.0.5.jar:webapp\target\dependency\log4j-api-2.13.3.jar:webapp\target\dependency\spring-jcl-5.3.6.jar:webapp\target\dependency\maven-artifact-manager-2.2.1.jar:webapp\target\dependency\spring-data-relational-2.1.8.jar:webapp\target\dependency\javax.json-1.0.4.jar:webapp\target\dependency\freemarker-2.3.31.jar:webapp\target\dependency\sisu-guava-0.9.9.jar:webapp\target\dependency\spring-boot-starter-data-jdbc-2.4.5.jar:webapp\target\dependency\spring-context-5.3.6.jar:webapp\target\dependency\maven-profile-2.2.1.jar:webapp\target\dependency\slf4j-api-1.7.30.jar:webapp\target\dependency\spring-boot-starter-web-2.4.5.jar:webapp\target\dependency\antlr-runtime-3.5.2.jar:webapp\target\dependency\spring-boot-starter-2.4.5.jar:webapp\target\dependency\maven-artifact-3.0.5.jar:webapp\target\dependency\spring-boot-starter-tomcat-2.4.5.jar:webapp\target\dependency\postgresql-42.2.19.jar:webapp\target\dependency\sisu-inject-bean-2.3.0.jar:webapp\target\dependency\plexus-component-annotations-1.5.5.jar:webapp\target\dependency\jackson-core-2.11.4.jar:webapp\target\dependency\tomcat-embed-websocket-9.0.45.jar:webapp\target\dependency\plexus-compiler-api-2.2.jar:webapp\target\dependency\spring-boot-devtools-2.4.5.jar:webapp\target\dependency\spring-boot-starter-jdbc-2.4.5.jar:webapp\target\dependency\spring-expression-5.3.6.jar:webapp\target\dependency\junit-4.13.2.jar:webapp\target\dependency\logback-classic-1.2.3.jar:webapp\target\dependency\maven-repository-metadata-2.2.1.jar:webapp\target\dependency\tomcat-embed-core-9.0.45.jar:webapp\target\dependency\classmate-1.5.1.jar:webapp\target\dependency\spring-session-jdbc-2.4.3.jar:webapp\target\dependency\HikariCP-3.4.5.jar:webapp\target\dependency\backport-util-concurrent-3.1.jar:webapp\target\dependency\javax.persistence-api-2.2.jar:webapp\target\dependency\log4j-to-slf4j-2.13.3.jar:webapp\target\dependency\spring-beans-5.3.6.jar:webapp\target\dependency\hibernate-validator-6.1.7.Final.jar:webapp\target\dependency\org.abego.treelayout.core-1.0.3.jar:webapp\target\dependency\snakeyaml-1.27.jar:webapp\target\dependency\jul-to-slf4j-1.7.30.jar:webapp\target\dependency\classworlds-1.1-alpha-2.jar:webapp\target\dependency\spring-boot-autoconfigure-2.4.5.jar:webapp\target\dependency\jboss-logging-3.4.1.Final.jar:webapp\target\dependency\spring-boot-starter-freemarker-2.4.5.jar:webapp\target\dependency\antlr4-maven-plugin-4.9.1.jar:webapp\target\dependency\jackson-annotations-2.11.4.jar:webapp\target\dependency\jackson-databind-2.11.4.jar:webapp\target\dependency\spring-context-support-5.3.6.jar:webapp\target\dependency\spring-boot-2.4.5.jar:webapp\target\dependency\maven-model-3.0.5.jar:webapp\target\dependency\jackson-datatype-jsr310-2.11.4.jar:webapp\target\dependency\spring-tx-5.3.6.jar:webapp\target\dependency\logback-core-1.2.3.jar:webapp\target\dependency\maven-settings-2.2.1.jar:webapp\target\dependency\maven-project-2.2.1.jar:webapp\target\dependency\jakarta.annotation-api-1.3.5.jar:webapp\target\dependency\plexus-utils-3.0.8.jar:webapp\target\dependency\spring-jdbc-5.3.6.jar:webapp\target\dependency\sisu-guice-3.1.0-no_aop.jar:webapp\target\dependency\jackson-datatype-jdk8-2.11.4.jar:webapp\target\dependency\antlr4-runtime-4.9.1.jar:webapp\target\dependency\spring-aop-5.3.6.jar:webapp\target\dependency\ST4-4.3.jar:webapp\target\dependency\spring-session-core-2.4.3.jar:webapp\target\dependency\antlr4-4.9.1.jar:webapp\target\dependency\maven-plugin-registry-2.2.1.jar:webapp\target\dependency\jakarta.el-3.0.3.jar:webapp\target\dependency\spring-web-5.3.6.jar:webapp\target\dependency\spring-data-commons-2.4.8.jar:webapp\target\dependency\hamcrest-2.2.jar:webapp\target\dependency\spring-boot-starter-validation-2.4.5.jar:webapp\target\dependency\sisu-inject-plexus-2.3.0.jar:webapp\target\dependency\spring-data-jdbc-2.1.8.jar:webapp\target\dependency\plexus-interpolation-1.11.jar:webapp\target\dependency\wagon-provider-api-1.0-beta-6.jar:webapp\target\dependency\spring-boot-starter-json-2.4.5.jar:webapp\target\dependency\spring-webmvc-5.3.6.jar:webapp\target\dependency\jakarta.validation-api-2.0.2.jar:webapp\target\dependency\spring-boot-starter-logging-2.4.5.jar:webapp\target\dependency\mindcode-compiler-1.1.0-SNAPSHOT.jar:webapp\target\dependency\hamcrest-core-2.2.jar:webapp\target\dependency\plexus-build-api-0.0.7.jar:webapp\target\dependency\icu4j-61.1.jar:webapp\target\dependency\plexus-classworlds-2.4.jar:webapp\target\dependency\jackson-module-parameter-names-2.11.4.jar:webapp\target\dependency\plexus-container-default-1.0-alpha-9-stable-1.jar info.teksol.mindcode.webapp.WebappApplication
```

Hopefully, this will allow you to start the server.

**Comment by IotaBread** [comment]
I think you meant @cyclotron3k...

**Comment by schittli** [comment]
Thank you very much for your help, @francois 

First a bit of facts :-)

### The PostgreSQL Database

If I start the older mindcode release, then the server starts perfectly:
```
git checkout 03ecee928ce36ae33303e2b37f428c2f63634adb
mvn clean compile exec:java
```

Additionally, if I test the connection to the database in the shell, the connection works fine.
Therefore, I guess:

1. If mindcode does not have different database requirements, now, 
2. then my connection string and my database is OK

**Comment by francois** [comment]
@ByMartrixx, my apologies... I looked at the author of #20, rather than who authored a commit.

@schittli, in ab1ad052502e8f24a404cc064ca9840316b38534, I split the project in two: there now exists Mindcode-the-compiler (`compiler/` folder) as well as Mindcode-the-webapp (`webapp/` folder). The top-level Maven file does not tell Maven how to run the webapp. The instructions are unclear.

Did you try the java command I posted above? The `./mvnw.cmd install` bit is super important: it builds the project and copies dependencies to the `webapp/target/dependencies` directory. I really expect the `java -classpath webapp\target\mindcode...` command to work. Could you paste the result of running both `./mvnw.cmd install` and `java -classpath ...` ?

**Comment by schittli** [comment]
Thank you, @francois!, 

before I address your previous comment, I have a question:

### is the Database connection hardcoded to `localhost:5432`?
could it be that the new code for the database connection no longer takes into account the environment variable JDBC_DATABASE_URL but is hardcoded to `localhost:5432`?

I was able to get `mvn clean test` running on Windows (one small note about it afterwards) and I've got the attached Test result file: `.\src\webapp\target\surefire-reports\info.teksol.mindcode.webapp.WebappApplicationTests.txt`

On Line 31 we can read:
```
nested exception is org.postgresql.util.PSQLException: 
Connection to localhost:5432 refused. 
Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

The Database Server is not on the local host `localhost:5432`.

But, maybe, it's just the test cases expecting the database server on localhost :-)

[info.teksol.mindcode.webapp.WebappApplicationTests.txt](https://github.com/francois/mindcode/files/6346005/info.teksol.mindcode.webapp.WebappApplicationTests.txt)

**Comment by schittli** [comment]
### `mvn clean test` is bound to linux because of calling 'diff'

The tests use Linux `diff`, therefore I get this error on Windows:
```
[ERROR] info.teksol.mindcode.webapp.SamplesTest.validateSamples  Time elapsed: 0.042 s  <<< ERROR!
java.io.IOException: Cannot run program "diff": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
```

I was able to fix it by replacing `diff` by `fc.exe`:

File: `\src\webapp\src\test\java\info\teksol\mindcode\webapp\SamplesTest.java`
```
final Process diff = new ProcessBuilder()
		.command("fc.exe", "-u", unoptimizedTarget.getAbsolutePath(), optimizedTarget.getAbsolutePath())
		.redirectOutput(diffTarget)
		.start();
```

I don't know if the Test-Engine is able to automatically distinguish between Linux and Windows, but Windows users can easily correct it with the above hint :-)

**Comment by francois** [comment]
Thanks for investigating this. It should be possible to distinguish between Linux/Unix & Windows and use the correct executable.

The difference with the previous version is that now the database configuration is coming from a file, rather than the environment. Please take a look at `webapp/src/main/resources/application.properties` and `webapp/src/test/resources/application.properties`: those files tell Spring what URL to use to contact PostgreSQL. You can change those files until a solution is found to enable reading the environment, rather than using application.properties.

Mindcode-the-webapp is deployed to Heroku, and I didn't have to configure anything special to make it work. Either Heroku discovers Spring and does the correct magic, or Spring detects the environment variable. I don't know which yet. I'll take a look at this sometime this week.

Given the above, I guess you should be able to both run the tests and start the app?

**Comment by schittli** [comment]
### mvn install

#### Configuring application.properties solves the issue 😊

> Did you try the java command I posted above? The ./mvnw.cmd install bit is super important

Thank you very much!, yes, I am processing each of your hints, but I was still describing the first results :-)

After I have configured the DB Connection Strings in:
`webapp/src/main/resources/application.properties`
`webapp/src/test/resources/application.properties`

Both commands worked fine 👌:
`mvn clean test`
`mvn install`


#### How can I start the App ❓

I'm sorry, I have another silly question:
I can no longer start the WebApp with this command: `mvn clean compile exec:java`.

Should this still work?

**Comment by schittli** [comment]
Sorry!, I've found your description:
```
 ./mvnw install
$ java -classpath $( find webapp -type f -name '*.jar' | tr '\n' ':' ) info.teksol.mindcode.webapp.WebappApplication
```
I'll try it :-)

**Comment by schittli** [comment]
### Starting the server - unfortunately I have no luck

Thank you very much for converting this command: `java -classpath $( find webapp -type f -name '*.jar' | tr '\n' ':' ) info.teksol.mindcode.webapp.WebappApplication` to Windows :-), as soon as starting the server works, I can easily convert the bash command to a nice powershell command so that others can use it, too.

I tried to start the server, unfortunately, it does not work:
```
# Build
.\mvnw.cmd install
…
[INFO] Reactor Summary:                                                            
[INFO]                                                                             
[INFO] Mindcode 1.0.0-SNAPSHOT ............................ SUCCESS [  0.626 s]    
[INFO] mindcode-compiler 1.1.0-SNAPSHOT ................... SUCCESS [  5.954 s]    
[INFO] mindcode-webapp 2.0.0-SNAPSHOT ..................... SUCCESS [ 18.740 s]    
[INFO] ------------------------------------------------------------------------    
[INFO] BUILD SUCCESS                                                               
…

# Start
java -classpath webapp\target\mindcode-webapp-2.0.0-SNAPSHOT.jar:webapp\target\dependency\spring-core-5.3.6.jar:webapp\target\dependency\maven-plugin-api-3.0.5.jar:webapp\target\dependency\log4j-api-2.13.3.jar:webapp\target\dependency\spring-jcl-5.3.6.jar:webapp\target\dependency\maven-artifact-manager-2.2.1.jar:webapp\target\dependency\spring-data-relational-2.1.8.jar:webapp\target\dependency\javax.json-1.0.4.jar:webapp\target\dependency\freemarker-2.3.31.jar:webapp\target\dependency\sisu-guava-0.9.9.jar:webapp\target\dependency\spring-boot-starter-data-jdbc-2.4.5.jar:webapp\target\dependency\spring-context-5.3.6.jar:webapp\target\dependency\maven-profile-2.2.1.jar:webapp\target\dependency\slf4j-api-1.7.30.jar:webapp\target\dependency\spring-boot-starter-web-2.4.5.jar:webapp\target\dependency\antlr-runtime-3.5.2.jar:webapp\target\dependency\spring-boot-starter-2.4.5.jar:webapp\target\dependency\maven-artifact-3.0.5.jar:webapp\target\dependency\spring-boot-starter-tomcat-2.4.5.jar:webapp\target\dependency\postgresql-42.2.19.jar:webapp\target\dependency\sisu-inject-bean-2.3.0.jar:webapp\target\dependency\plexus-component-annotations-1.5.5.jar:webapp\target\dependency\jackson-core-2.11.4.jar:webapp\target\dependency\tomcat-embed-websocket-9.0.45.jar:webapp\target\dependency\plexus-compiler-api-2.2.jar:webapp\target\dependency\spring-boot-devtools-2.4.5.jar:webapp\target\dependency\spring-boot-starter-jdbc-2.4.5.jar:webapp\target\dependency\spring-expression-5.3.6.jar:webapp\target\dependency\junit-4.13.2.jar:webapp\target\dependency\logback-classic-1.2.3.jar:webapp\target\dependency\maven-repository-metadata-2.2.1.jar:webapp\target\dependency\tomcat-embed-core-9.0.45.jar:webapp\target\dependency\classmate-1.5.1.jar:webapp\target\dependency\spring-session-jdbc-2.4.3.jar:webapp\target\dependency\HikariCP-3.4.5.jar:webapp\target\dependency\backport-util-concurrent-3.1.jar:webapp\target\dependency\javax.persistence-api-2.2.jar:webapp\target\dependency\log4j-to-slf4j-2.13.3.jar:webapp\target\dependency\spring-beans-5.3.6.jar:webapp\target\dependency\hibernate-validator-6.1.7.Final.jar:webapp\target\dependency\org.abego.treelayout.core-1.0.3.jar:webapp\target\dependency\snakeyaml-1.27.jar:webapp\target\dependency\jul-to-slf4j-1.7.30.jar:webapp\target\dependency\classworlds-1.1-alpha-2.jar:webapp\target\dependency\spring-boot-autoconfigure-2.4.5.jar:webapp\target\dependency\jboss-logging-3.4.1.Final.jar:webapp\target\dependency\spring-boot-starter-freemarker-2.4.5.jar:webapp\target\dependency\antlr4-maven-plugin-4.9.1.jar:webapp\target\dependency\jackson-annotations-2.11.4.jar:webapp\target\dependency\jackson-databind-2.11.4.jar:webapp\target\dependency\spring-context-support-5.3.6.jar:webapp\target\dependency\spring-boot-2.4.5.jar:webapp\target\dependency\maven-model-3.0.5.jar:webapp\target\dependency\jackson-datatype-jsr310-2.11.4.jar:webapp\target\dependency\spring-tx-5.3.6.jar:webapp\target\dependency\logback-core-1.2.3.jar:webapp\target\dependency\maven-settings-2.2.1.jar:webapp\target\dependency\maven-project-2.2.1.jar:webapp\target\dependency\jakarta.annotation-api-1.3.5.jar:webapp\target\dependency\plexus-utils-3.0.8.jar:webapp\target\dependency\spring-jdbc-5.3.6.jar:webapp\target\dependency\sisu-guice-3.1.0-no_aop.jar:webapp\target\dependency\jackson-datatype-jdk8-2.11.4.jar:webapp\target\dependency\antlr4-runtime-4.9.1.jar:webapp\target\dependency\spring-aop-5.3.6.jar:webapp\target\dependency\ST4-4.3.jar:webapp\target\dependency\spring-session-core-2.4.3.jar:webapp\target\dependency\antlr4-4.9.1.jar:webapp\target\dependency\maven-plugin-registry-2.2.1.jar:webapp\target\dependency\jakarta.el-3.0.3.jar:webapp\target\dependency\spring-web-5.3.6.jar:webapp\target\dependency\spring-data-commons-2.4.8.jar:webapp\target\dependency\hamcrest-2.2.jar:webapp\target\dependency\spring-boot-starter-validation-2.4.5.jar:webapp\target\dependency\sisu-inject-plexus-2.3.0.jar:webapp\target\dependency\spring-data-jdbc-2.1.8.jar:webapp\target\dependency\plexus-interpolation-1.11.jar:webapp\target\dependency\wagon-provider-api-1.0-beta-6.jar:webapp\target\dependency\spring-boot-starter-json-2.4.5.jar:webapp\target\dependency\spring-webmvc-5.3.6.jar:webapp\target\dependency\jakarta.validation-api-2.0.2.jar:webapp\target\dependency\spring-boot-starter-logging-2.4.5.jar:webapp\target\dependency\mindcode-compiler-1.1.0-SNAPSHOT.jar:webapp\target\dependency\hamcrest-core-2.2.jar:webapp\target\dependency\plexus-build-api-0.0.7.jar:webapp\target\dependency\icu4j-61.1.jar:webapp\target\dependency\plexus-classworlds-2.4.jar:webapp\target\dependency\jackson-module-parameter-names-2.11.4.jar:webapp\target\dependency\plexus-container-default-1.0-alpha-9-stable-1.jar info.teksol.mindcode.webapp.WebappApplication

# Result
Error: Main Class info.teksol.mindcode.webapp.WebappApplication couldn't be found or loaded
Reason: java.lang.ClassNotFoundException: info.teksol.mindcode.webapp.WebappApplication
```
### What I have already tried to get it up and running

- Just to be sure, I have changed the Classpath list from `webapp\target` to `.\webapp\target` - it does not work
- I have changed the Classpath list so that it uses absolute paths - it does not work
- because the manifest file: `mindcode-webapp-2.0.0-SNAPSHOT.jar\META-INF\MANIFEST.MF` does not have a `Main-Class` definition, I changed it to:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.6.3
Built-By: schittli
Build-Jdk: 11.0.10
Main-Class: info.teksol.mindcode.webapp.WebappApplication
```
unfortunately, it does not solve the issue


It's a pity Java didn't get a smart startup behaviour after all these years. I'm pretty sure Java knows why it doesn't find the class - or it could at least provide a parameter that lists all the classes it found :-)

**Comment by schittli** [comment]
### starting the webserver works on Windows, too 😁

I've found the issue: 
If I start Java.exe, it still shows insufficient help - but it gives an exciting hint:
```
    -cp <classpath with directories and ZIP/JAR files>
    -classpath <class search path with directories and ZIP/JAR files>
    --class-path <class search path with directories and ZIP/JAR files>
                  A list of directories, JAR archives and ZIP archives separated by ;.
                  and ZIP archives where class files are searched for.
```
On Windows, they talk about `;` and not `:` to delimit the paths ☹️

Therefore, I tried this PowerShell command which searches all jar files in .\webapp and joins them by `;`
```PowerShell
java -classpath "$((Get-ChildItem .\webapp\ *.jar -Recurse | select -ExpandProperty FullName) -join ';')" info.teksol.mindcode.webapp.WebappApplication
```

And it works 😊

**Comment by schittli** [comment]
You can close the ticket, 
### I just create a summary of this issue

On Windows, after Relese [03ecee9](https://github.com/francois/mindcode/commit/03ecee928ce36ae33303e2b37f428c2f63634adb) up to Release [de1c3b0](https://github.com/francois/mindcode/commit/de1c3b0c6637bdadd90cf00133a78e97806f8f22):

- [ ] The DB Connection string must be configured in two files:
`webapp/src/main/resources/application.properties`
`webapp/src/test/resources/application.properties`
- [ ] To start the Unit tests, call: `.\mvnw.cmd clean test`
- [ ] To compile mindcode, call: `.\mvnw.cmd install`
- [ ] To start the Webserver, call: `java -classpath "$((Get-ChildItem .\webapp\ *.jar -Recurse | select -ExpandProperty FullName) -join ';')" info.teksol.mindcode.webapp.WebappApplication`

Thanks a lot, kind regards,
Thomas
