### ISSUE TITLE
Parameters in functions are not preserved

### ISSUE THREAD

**Issue by francois** [cardillan/mindcode#36]
for example: 

```
allocate stack in bank1

def T(n)
  if n>0
    print(n)
    T(n-1)
    print(n)
  end
end

T(2)
printflush(message1)
```

in this case, n becomes a local. I would expect the output of this program to be: 2112
but it is not, and it seems like n is being globally altered in the recursive function, which makes sense in Logic. The project seems to go though much effort to push return addresses and parameters on the stack, but locals are not maintained (it seems).

Am I understanding this wrong? Did I write my program above incorrectly to expect 2112 as the output? Although I haven't figured out why... the program actually prints "20" and that's it. If I do T(3) it will print "30" and that's it.

I am interested in understanding this better!

_Originally posted by @TheAtomAnt in https://github.com/francois/mindcode/discussions/34_

**Comment by francois** [comment]
In this case, `n` should have been stored on the stack, before entering the function's body, and restored on exit.

In essence, the generated code should look like (pseudo Mindustry Logic):

```
call T(2)
end

label T
__tmpX = pop
push n
set n = __tmpX
// function body
n = pop
@counter = pop // jump to caller
```

If there are more than one parameters, the same `__tmpX` should be reused, to prevent exhaustion of local variables in Mindustry Logic. There must be a limit somewhere, and it would be preferable not to hit it.

**Comment by cardillan** [comment]
Functions have been improved in March 2023 update. Local scope for function variables is now correctly preserved in both recursive and non-recursive functions; recursive functions store and preserve function parameters and  variables on stack (see https://github.com/francois/mindcode/blob/main/SYNTAX.markdown#custom-functions).
