### ISSUE TITLE
Ternary expression generated wrong

### ISSUE THREAD

**Issue by tomforwood** [cardillan/mindcode#40]
```
ore1 = @lead
ore2 = @coal
container = container1
    o1 = container.ore1
    o2 = container.ore2
    ore = o1>o2? ore2 : ore1
```
generated
```
sensor o1 container @ore1
sensor o2 container @ore2
jump 16 notEqual o2 true
set __tmp9 ore2
jump 17 always 0 0
set __tmp9 ore1
op greaterThan ore o1 __tmp9
```
It should be something like
```
sensor o1 container @ore1
sensor o2 container @ore2
jump 16 lessThanEq o1 o2
set ore ore2
jump 17 always 0 0
set ore ore1
```

**Comment by tomforwood** [comment]
Workaround : use if style syntax
There appears to be a second bug, ore1 and ore2 have been made into constants, @ore1 and @ore2 when they should be variables

**Comment by cardillan** [comment]
You can use the dot syntax (container.resource) only if the resource denotes an existing ore, and you omit the leading `@`: `container.copper`.

If you want to obtain the level of item specified by a variable, you need to call sensor function: `container.sensor(ore)`

Also, if you compile just the code snippet you've posted, lots of instructions get lost to dead code elimination. We can mark the final output as 'not dead' by printing it, for example.

The last problem is that the ternary operator takes precedence over the greater-than comparison.

Your example, when modified with respect to the above rules, looks like this:
```
ore1 = @lead
ore2 = @coal
container = container1
o1 = container.sensor(ore1)
o2 = container.sensor(ore2)
ore = (o1 > o2) ? ore2 : ore1
print(ore)
```
produces

```
set ore1 @lead
set ore2 @coal
set container container1
sensor o1 container ore1
sensor o2 container ore2
jump 8 lessThanEq o1 o2
set __tmp3 ore2
jump 9 always 0 0
set __tmp3 ore1
set ore __tmp3
print ore
end
```
I don't think there's anything wrong about it as of now.
