### ISSUE TITLE
uradar() parameters wrong

### ISSUE THREAD

**Issue by marralesfios** [cardillan/mindcode#51]
this: `uradar(enemy,any,any,distance,0,1,rslt)`
generates this:
```
set __tmp0 0
uradar enemy any any distance __tmp0 __tmp1 __tmp2
```
where __tmp0 is supposed to be the order, __tmp1 should be the `found` output, and `__tmp2` should be the dest.
However, the processor UI shows:
"target enemy and any and any order __tmp1 sort distance outpot __tmp2
That is, __tmp0 is ignored, and __tmp1 is used as the `order` input, which is NULL.
Furthermore, this, used as an `if` condition, jumps over the statement if (tmp2!=true),
it should actually be (tmp2===null).(Don't rely on automatic type conversion unless you must!)

**Comment by marralesfios** [comment]
Possibly related:
https://github.com/francois/mindcode/issues/39

**Comment by cardillan** [comment]
There might have been originally problems with this instruction. At this point, the correct syntax for this function call is
```
result = uradar(enemy,any,any,distance, 1)
```
which produces
```
uradar enemy any any distance 0 1 result
```
Note that the fifth argument (`0`) in this instruction is unused -- the `uradar` instruction has the same argument list as `radar` instruction, and there the fifth argument corresponds to the turret performing the radar operation.

See  [Function reference for Mindustry Logic 7](../blob/main/FUNCTIONS_V7.markdown#instruction-uradar).
