### ISSUE TITLE
BREAK statement does not compile

### ISSUE THREAD

**Issue by VladFurman** [cardillan/mindcode#55]
Following code does not compile when break statement included. When commented out, compiles.

allocate stack in cell1

```
n = 0
reactor = getlink(n)
lowest = 1
while reactor != null
    print("type: ", reactor.type)
    if (reactor.type != @thorium-reactor)
        print("not reactor!")
        break
    end
    pct_avail = reactor.cryofluid / reactor.liquidCapacity
    lowest  = (pct_avail < lowest) ? pct_avail : lowest
    // print(n, ": pct_avail is: ",pct_avail,"\n")
    reactor.enabled = pct_avail >= 0.25   
    n += 1
    reactor = getlink(n)    
end
print("lowest is: ",lowest)
printflush(message1)
```

**Comment by cardillan** [comment]
@francois, I have implemented the break and continue statements in the most basic form -- they affect the innermost loop. I'll create a PR for it eventually.

However, I thought about possible improvements:

1. Some languages (not Ruby, though) have means to break/continue other than the innermost loop. In Java there can be a label attached to the loop; `break <label>` then exits the labelled loop. Would you be interested in this feature? I don't have a need for it at the moment, but if you envisioned it in Mindcode, I'd give it a try.
2. Some languages (Ruby excluded again) use `break` in switch/case statements. Is this something you'd want in Mindcode?

**Comment by francois** [comment]
I never gave labelled break/continue a thought, but I wouldn’t mind them. Adding break in switch/case would invalidate any existing code. I would not want that.
