### ISSUE TITLE
Function with no parameters causes compilation error.

### ISSUE THREAD

**Issue by VladFurman** [cardillan/mindcode#56]
Same function, when it has a parameter, even if unused, compiles. When it does not, error:
`Syntax error: [@42,182:184='def',<5>,17:0] on line 17:0: mismatched input 'def' expecting <EOF>`

Example code:
```
allocate stack in cell1

def delay(n, fps)
  _x = 0
  deadline = @tick + n * fps
  while @tick < deadline
    _x += 1
  end
end

def delay2(n)
  print("test")
end

def delay3()
  print("test")
end

delay(1, 60)
delay2(1)
delay3()
```

**Comment by cardillan** [comment]
The problem was that the compiler originally expected parameterless functions to be declared without parentheses, eg.
```
def delay3
  print("test")
end
```
As of now, both ways to declare parameterless functions (ie. with or without parentheses) are supported.
