### ISSUE TITLE
getlink doesn't prevent parameter from being eliminated by optimization

### ISSUE THREAD

**Issue by cardillan** [cardillan/mindcode#59]
Variables passed to the getlink function aren't considered used and are eliminated by optimization. For example, this code:
```
index1 = 1
index2 = 2
print(index2)
block0 = getlink(0)
block1 = getlink(index1)
block2 = getlink(index2)
print(block0)
print(block1)
print(block2)
```
compiled with optimization produces this output:
```
set index2 2
print index2
getlink block0 __tmp2
getlink block1 index1
getlink block2 index2
print block0
print block1
print block2
end
```
The output is missing set instructions to set index1 and __tmp2 variables. Setting index2 is included, as it figures in the print instruction.

A workaround is to use other operation to mark the variable as used, as demonstrated with the index2 variable.

**Comment by cardillan** [comment]
I'm completely new to ANTLR, but perhaps the problem is in the DeadCodeEliminator class, where instead of this
```
    private void visitGetlink(LogicInstruction instruction) {
        reads.add(instruction.getArgs().get(0));
    }
```

should be

```
    private void visitGetlink(LogicInstruction instruction) {
        addWrite(instruction, 0);
        reads.add(instruction.getArgs().get(1));
    }
```
as the getlink instruction syntax is `getlink out index`

**Comment by francois** [comment]
You are most likely right. I have not looked at the code in a long while. Can you provide a PR for this? Thanks!FrançoisLe 5 janv. 2023 à 06:26, cardillan ***@***.***> a écrit :﻿
I'm completely new to ANTLR, but perhaps the problem is in the DeadCodeEliminator class, where instead of this
    private void visitGetlink(LogicInstruction instruction) {
        reads.add(instruction.getArgs().get(0));
    }

should be
    private void visitGetlink(LogicInstruction instruction) {
        addWrite(instruction, 0);
        reads.add(instruction.getArgs().get(1));
    }

as the getlink instruction syntax is getlink out index

**Comment by cardillan** [comment]
I verified the change locally -- I got the expected result, and I've created the pull request. It's my first one, so I hope I didn't mess up anything. It looked okay-ish to me.
