### ISSUE TITLE
Info: VSCode Syntax Highligher for Mindcode published :-)

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#6]
Hello @francois 

### VS Code Extension: mindcode (Syntax Highlighter for the Mindcode Syntax / Grammar)

Because I constantly had problems recognising the associated `if` / `end` in Mindcode and because of the copy/paste I constantly overlooked wrong `==` and `=`. Therefore I wrote a small extension for Mindcode for Visual Studio Code to highlight the Mindcode Syntax / Grammar.

![image](https://user-images.githubusercontent.com/8282673/112750180-43947a00-8fc7-11eb-8a22-83be7624753e.png)

I cannot promise that I will be able to maintain it reliably, but at least it is already a help today :-)

Here is a Screenshot of the Extension in VS Code:
![image](https://user-images.githubusercontent.com/8282673/112750277-08467b00-8fc8-11eb-9da0-e06308e21dbf.png)

Kind regards,
Thomas

**Comment by francois** [comment]
Hey wow! This is super cool. Can you provide a link to the extension? I can link that from the README, pointing people to it. Thanks for your time!

**Comment by francois** [comment]
@schittli, unrelated to the ticket itself, but your while loop can be slightly improved:

```
while (thisBlock = getlink(idxN)) != null
  // ...
  idxN += 1
end
```

**Comment by IotaBread** [comment]
Here is the extension
https://marketplace.visualstudio.com/items?itemName=TomSchi.mindcode

**Comment by schittli** [comment]
Thank you, @francois, for the improved and nice-looking while loop!
I had a lot to fight with unexpected behaviours in Mindustry Logic / Mindcode, therefore I went back to the roots and simple (not nested) commands 😅
