### ISSUE TITLE
Command-line compiler and optimizers restructuralization

### ISSUE THREAD

**Issue by cardillan** [cardillan/mindcode#70]
I plan to implement the following restructuralizations as part of this issue:
- Move the **CompileMain** and **CompilerFacade** from the webapp project to the compiler project. I believe the command-line compiler doesn't belong to the webapp project. @francois, I'm not sure you won't object to the **CompilerFacade** being moved over there as well - if you do, let me know, I'll refactor it. There aren't any unit tests affected by this change. (The main motivation is that the webapp project has unit tests that fail when PostgreSQL isn't running, while the compiler project builds without any problem.)
  - `mindcode.bat` will be created to run the command line compiler in Windows,
  - `mindcode` script for Linux will be updated to reflect the change of path to compiler jars -- the change is simple, but **I won't be able to test it after the change**.
- Restructure the creation of logic instruction pipeline. I'll create an enum with constants representing individual optimizers and a method to return an instance of the optimizer. The pipeline will be built from all existing enums in reverse order. This will allow us to:
  - easily reorder the optimization pipeline if needed,
  - add support for parametrized activation/deactivation of individual optimizers (I'll implement command line support first, as I'm not a front-end guy).
  - easily build custom pipelines for unit tests,
  - allow error, warning and informational messages to be generated by the optimizers and then displayed. The idea is to allow dead code elimitator to display a list of eliminated variables, and a list of variables that are read, but never written to. As we lack formal checks for variable declaration, this will help catch typos in variable names. Again, I'll add support to the command-line compiler first.

**Comment by francois** [comment]
Your plan sounds great to me. Go ahead with those changes.
