### ISSUE TITLE
Mindustry Logic: Probably missing op commands

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#9]
Good evening

I have tried to use the max() function and I've got this error:
```
a = max(1,2)
Don't know how to handle function named [max]
```

Therefore I have tested all Mindustry Logic `op` commands and I guess that those are missing: (I have created a task list if someone would like to fix them :-))

- [x] log(10)
`op log10 result param1 param2`
- [x] 2d simplex noise
`op noise result param1 param2`
- [x] length of a vector
`op len result param1 param2`
- [x] Angle of a vector in degree
`op angle result param1 param2`
- [x] max of two numbers
`op max result param1 param2`
- [x] min of two numbers
`op min result param1 param2`
- [x] Bitwise and
`op and result param1 param2`
- [x] Bitwise xor
`op xor result param1 param2`
- [x] Bit shift left
`op shl result param1 param2`
- [x] Bit shift right
`op shr result param1 param2`
- [x] Integer division
`op idiv result param1 param2`

Kind regards,
Thomas

**Comment by francois** [comment]
This is really helpful. Thanks for your time in compiling the list. I’ll implement those in the coming days.

François

**Comment by schittli** [comment]
Good morning 🙂,

you're sooooo fast!, I've just tested the generated compiler code for those commits:
- a11c151
- 994e585
and it's perfect.

Thanks a lot, kind regards,
Thomas
