### ISSUE TITLE
Schematics builder

### ISSUE THREAD

**Issue by cardillan** [cardillan/mindcode#90]
This is about a feature I plan to add to Mindcode, although it probably will take some time.

My typical workflow with Mindcode is currently centered around code development. I write and compile code, then paste it into some processor in one of my game saves to test it, and when it looks good I update the schematics containing the entire setup. This is sometimes bothersome - I might forget whether I've updated a particular schematics, I might need to build the schematics afresh to get the processor and all contained blocks to an initial state, and I need to type the name again when saving the updated schematics back.

Therefore I'm going to create a schematics builder. It would provide two main functionalities:
- decompile existing schematics into a definition file.
- build schematics from a definition file and Mindcode codes for any processors in the schematics.

Obviously there would be a command-line version for both of these functions, but since inputs and outputs are both texts, it is quite straightforward to add support to the webapp as well.

The usage I envision is this:

1. Create the schematics in Mindustry.
2. Export the schematics via clipboard or to a file.
3. Decompile the schematics to obtain definition file.
4. Insert/replace code for processors (decompiled schematics would contain mlog, schema builder would support both mlog and Mindcode to be bundled with processors)
5. Compile the schema (Mindcode gets compiled automatically).
6. Export the schematics to clipboard/file.

It should be possible - and quite simple - co create simpler schematics definition by hand from scratch, for example if the schematics should contain just the processor and a few basic objects (switch, message, memory cell).

Schematics structure isn't that complicated: basically it is a list of tiles with their positions, contained types, rotation and block type-specific configuration. Processor code and linked blocks are encoded in this configuration.

At this point I'm not sure what format or syntax to use for the schematics definition. Initial version should allow to:
- specify  schematics metadata (name, description, labels and tags)
- place blocks at positions within the schema
- assign symbolic names to certain blocks, used to specify links (not just processors, bridges and nodes need to get linked too)
- specify configuration for each block that supports it (eg. sorter/unloader item selection, bridge targets)
- specify blocks linked to processors and their names
- specify Mindcode/mlog code to use with each processor (embedded to schema definition or, in case of the command line compiler, from a file)

Some future version might provide additional functionality to:
- fill an area with blocks of the same type - eg. plastanium wall from (0,0) to (10,0)
- provide additional means to define block layout, eg. left-to-right, top-to-bottom list or relative block placement
- automatically link all named blocks to a processor
- use identical code for several processors, with possible alterations (eg. by setting variables or constants that could be referenced from the shared code).

**Comment by cardillan** [comment]
Update: I've completed a working prototype, still need to create web app interface for the thing and do some more testing.

As a preview, here's a code defining a simple schematics:

```
schematics
    name = "On/off switch"
    description = """
        Enables/disables linked blocks according to switch state.

        Usage: link blocks to be controlled, use switch to enable/disable them.
        """
    label = BLOCK-MICRO-PROCESSOR
    dimensions = (2, 1)
switch1:
    @switch              at (0, 0) facing south enabled
    @micro-processor     at (1, 0) facing south processor
        links
            switch1 as switch1
        end
        mindcode = """
            on = switch1.enabled
            // Starting at 1, we want to skip the switch
            for link in 1 ... @links
                device = getlink(link)
                device.enabled = on
            end
            """
    end
end

```

A little larger one:

```
schematics
    name = "Healing Center"
    description = """
        Automatically recalls damaged polys and megas for healing.
        """
    label = BLOCK-REPAIR-POINT
    dimensions = (5, 5)
    @power-node          at (0, 0) facing west  connected to (0, 1), (0, 2), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2)
    @repair-point        at (0, 1) facing east 
    @repair-point        at (0, 2) facing east 
    @repair-point        at (0, 3) facing east 
    @power-node          at (0, 4) facing west  connected to (0, 2), (0, 3), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4)
    @repair-point        at (1, 0) facing east 
    @repair-point        at (1, 1) facing east 
    @micro-processor     at (1, 2) facing east  processor
        mlog = """
           ubind @mega
           sensor health @unit @health
           sensor max @unit @maxHealth
           jump 5 equal health max
           ucontrol move @thisx @thisy 0 0 0
           end
           """
    end
    @repair-point        at (1, 3) facing east 
    @repair-point        at (1, 4) facing east 
    @repair-point        at (2, 0) facing east 
    @repair-point        at (2, 1) facing east 
    @repair-point        at (2, 2) facing east 
    @repair-point        at (2, 3) facing east 
    @repair-point        at (2, 4) facing east 
    @repair-point        at (3, 0) facing east 
    @repair-point        at (3, 1) facing east 
    @micro-processor     at (3, 2) facing east  processor
        mlog = """
           ubind @poly
           sensor health @unit @health
           sensor max @unit @maxHealth
           jump 5 equal health max
           ucontrol move @thisx @thisy 0 0 0
           end
           """
    end
    @repair-point        at (3, 3) facing east 
    @repair-point        at (3, 4) facing east 
    @power-node          at (4, 0) facing west  connected to (4, 1), (4, 2), (3, 0), (3, 1), (2, 0), (2, 1), (2, 2)
    @repair-point        at (4, 1) facing east 
    @repair-point        at (4, 2) facing east 
    @repair-point        at (4, 3) facing east 
    @power-node          at (4, 4) facing west  connected to (4, 3), (4, 2), (3, 4), (3, 3), (2, 4), (2, 3), (2, 2)
end
```

I believe the syntax is quite self-descriptive.

Another good news is that it is fairly easy to have the compiled schematics automatically update in Mindustry, through a very simple mod that will be part of the solution.

**Comment by cardillan** [comment]
Schematics Builder has been just deployed.

**Comment by k88936** [comment]
allowing gui to add & move blocks will be even better

**Comment by cardillan** [comment]
> allowing gui to add & move blocks will be even better

That would be cool. I don't see implementing something like that myself, though, front end isn't by strong suit.

What I would like to have is a renderer to display the created schematics on the webpage (that might even be a first, very small step towards a full fledged editor). I was trying to look around for something already made I could embed into the webapp easily, but to no avail at the moment.

**Comment by cardillan** [comment]
The Schematics builder seems to be stable and usable in its current form. While there is some further development [planned](https://github.com/cardillan/mindcode/blob/main/ROADMAP.markdown#schematics-builder), I'm currently concentrating on the compiler.
